### ISSUE TITLE
Checkout Page/Screen

### ISSUE THREAD

**Issue by Arch997** [Quwaysim/Coffee-To-Go#3]
Implement the checkout UI where the user can confirm their order.

**Comment by Quwaysim** [comment]
This is a modalbottom sheet, yes? @Arch997

**Comment by Arch997** [comment]
Modalbottom sheet?  You mean the page. I though it was the third screen. The screen where the order is confirmed.

**Comment by Arch997** [comment]
Ohh! I've only just seen what you meant now. I'm working on the page and I observed the close icon. So yeah, I imagine it's a bottom sheet.
